clone:
  git:
    image: plugins/git
    depth: 50
    recursive: true

pipeline:
  test:
    image: dealroom/php:1.3-${PHP_VERSION}
    volumes:
    - /home/ubuntu/ci-data/composer-cache-sh:/root/.composer/cache
    commands:
    - php -v
    - composer -V
    - composer install --prefer-dist -n -q
    - ./vendor/bin/phpunit

  slack:
    image: plugins/slack
    channel: system
    webhook: https://hooks.slack.com/services/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
    when:
      status: [ success, failure ]

matrix:
  PHP_VERSION:
  - 7.2
