name: Renovate Sync Action
description: Sets up and runs Renovate with configurable options

inputs:
  dealroomba-app-id:
    description: The GitHub App ID for Dealroomba
    required: true
  dealroomba-app-private-key:
    description: The private key for the Dealroomba GitHub App
    required: true
  app-token-permissions:
    description: Permissions for the generated app token
    required: false
    default: metadata:read,contents:write,workflows:write,issues:write,pull_requests:write
  gcp-auth-environment:
    description: Environment for GCP authentication
    required: false
    default: development
  renovate-config-file:
    description: Path to the Renovate configuration file
    required: false
    default: default-self-hosted.json5
  renovate-autodiscover-filter:
    description: Filter for Renovate autodiscovery (e.g., ${{ github.repository }})
    required: false
    default: ${{ github.repository }}

runs:
  using: composite
  steps:
    - name: Generate Token
      id: app-token
      uses: ./.github/actions/github-app-token
      with:
        application-id: ${{ inputs.dealroomba-app-id }}
        application-private-key: ${{ inputs.dealroomba-app-private-key }}
        permissions: ${{ inputs.app-token-permissions }}
    - name: Checkout Repository (with app token)
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        token: ${{ steps.app-token.outputs.token }}
        persist-credentials: false
    - name: Authenticate to Google Cloud
      id: gcp_auth
      uses: ./.github/actions/gcp-auth
      with:
        environment: ${{ inputs.gcp-auth-environment }}
    - name: Run Renovate
      uses: renovatebot/github-action@c3216113121a7c690027cd21eaad8a318c58bbcd # v38.1.4
      env:
        RENOVATE_HOST_RULES: |
          [
            {
              "matchHost": "github.com",
              "token": "${{ steps.app-token.outputs.token }}"
            },
            {
              "matchHost": "europe-docker.pkg.dev",
              "username": "oauth2accesstoken",
              "password": "${{ steps.gcp_auth.outputs.access-token }}"
            },
            {
              "hostType": "docker",
              "matchHost": "ghcr.io",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.GITHUB_TOKEN }}"
            },
            {
              "hostType": "git-tags",
              "matchHost": "github.com",
              "token": "${{ steps.app-token.outputs.token }}"
            },
            {
              "hostType": "github-releases",
              "matchHost": "github.com",
              "token": "${{ steps.app-token.outputs.token }}"
            },
            {
              "hostType": "packagist",
              "matchHost": "github.com",
              "token": "${{ steps.app-token.outputs.token }}"
            }
          ]
        LOG_LEVEL: debug
        RENOVATE_AUTODISCOVER: true
        RENOVATE_AUTODISCOVER_FILTER: ${{ inputs.renovate-autodiscover-filter }}
        RENOVATE_PLATFORM: github
        RENOVATE_PLATFORM_COMMIT: true
        RENOVATE_BOT_NAME: dealroomba-app[bot]
      with:
        configurationFile: ${{ inputs.renovate-config-file }}
        token: ${{ steps.app-token.outputs.token }}
