name: Renovate Sync Action
description: Sets up and runs Renovate with configurable options

inputs:
  dealroomba-app-id:
    description: The GitHub App ID for Dealroomba
    required: true
  dealroomba-app-private-key:
    description: The private key for the Dealroomba GitHub App
    required: true
  gcp-auth-environment:
    description: Environment for GCP authentication
    required: false
    default: development
  renovate-autodiscover-filter:
    description: Filter for Renovate autodiscovery (e.g., a specific repository name)
    required: false
  github-token:
    description: GitHub token for authenticating Renovate operations (usually secrets.GITHUB_TOKEN for GHCR)
    required: true

runs:
  using: composite
  steps:
    - name: Generate Token
      id: app-token
      uses: ./.github/actions/github-app-token
      with:
        application-id: ${{ inputs.dealroomba-app-id }}
        application-private-key: ${{ inputs.dealroomba-app-private-key }}
    - name: Checkout Repository (with app token)
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        token: ${{ steps.app-token.outputs.token }}
    - name: Check if gcp-auth action exists
      id: check-gcp-auth
      uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3.0.0
      with:
        files: ./.github/actions/gcp-auth/action.yml
    - name: Authenticate to Google Cloud
      id: gcp_auth
      if: steps.check-gcp-auth.outputs.files_exists == 'true'
      uses: ./.github/actions/gcp-auth
      with:
        environment: ${{ inputs.gcp-auth-environment }}
    - name: Cache Renovate Data
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: /home/ubuntu/.cache/renovate
        key: ${{ runner.os }}-renovate-cache-v1
    - name: Run Renovate
      uses: renovatebot/github-action@e854b273e774bce1ef8cb05f128b8ce8aee2a887 # v42.0.1
      env:
        RENOVATE_HOST_RULES: |
          [
            {
              "matchHost": "europe-docker.pkg.dev",
              "username": "oauth2accesstoken",
              "password": "${{ steps.gcp_auth.outputs.access-token }}"
            },
            {
              "hostType": "docker",
              "matchHost": "ghcr.io",
              "username": "${{ github.actor }}",
              "password": "${{ inputs.github-token }}"
            },
            {
              "hostType": "git-tags",
              "matchHost": "github.com",
              "token": "${{ steps.app-token.outputs.token }}"
            },
            {
              "hostType": "github-releases",
              "matchHost": "github.com",
              "token": "${{ steps.app-token.outputs.token }}"
            },
            {
              "hostType": "packagist",
              "matchHost": "github.com",
              "token": "${{ steps.app-token.outputs.token }}"
            }
          ]
        LOG_LEVEL: debug
        RENOVATE_AUTODISCOVER: true
        RENOVATE_ONBOARDING: false
        RENOVATE_AUTODISCOVER_FILTER: ${{ inputs.renovate-autodiscover-filter }}
        RENOVATE_PLATFORM: github
        RENOVATE_BOT_NAME: dealroomba-app[bot]
        RENOVATE_CACHE_DIR: /home/ubuntu/.cache/renovate
        RENOVATE_CACHE_PRIVATE_PACKAGES: true
        RENOVATE_REPOSITORY_CACHE_TYPE: local
        RENOVATE_OPTIMIZE_FOR_DISABLED: true
        RENOVATE_REPOSITORY_CACHE: enabled
      with:
        configurationFile: ./.github/renovate.json5
        token: ${{ steps.app-token.outputs.token }}
