name: Semver Get Next Version
description: Get the next version based on the latest tag
inputs:
  github-token:
    description: GitHub token to use for retrieving the latest tag
    required: true
  tag-prefix:
    description: |
      A prefix that will be striped when parsing tags (e.g. foobar/).
      Any other prefix will be ignored. Useful for monorepos.
    required: false
outputs:
  current:
    description: Current version number / latest tag.
    value: ${{ steps.semver.outputs.current }}
  next:
    description: Next version number in format v0.0.0
    value: ${{ steps.semver.outputs.next }}
runs:
  using: composite
  steps:
    - name: Get Next Version
      id: semver
      uses: ietf-tools/semver-action@778d1d5b7af80aa43f50104116b8363e7fc0d1ef # v1.10.1
      with:
        token: ${{ inputs.github-token }}
        prefix: ${{ inputs.tag-prefix }}
        skipInvalidTags: true
        fallbackTag: v0.0.0
        # Mapping conventional commits to semver (config-conventional)
        # @see https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum
        minorList: feat
        patchList: build, chore, ci, docs, fix, perf, refactor, revert, style, test
