name: Github Pull Request
description: Create a new GitHub pull request
inputs:
  github-token:
    description: GitHub token to use for creating the PR
    required: true
  branch:
    description: The branch to create the PR from
    required: false
    default: auto/pr
  commit-message:
    description: The commit message for the PR
    required: true
  add-paths:
    description: List of files to add to the PR (comma or newline-separated)
    required: false
  labels:
    description: List of labels to add to the PR (comma or newline-separated)
    required: false
    default: sync
outputs:
  pull-request-number:
    description: Pull request number created for the version bump
    value: ${{ steps.create-pr.outputs.pull-request-number }}
runs:
  using: composite
  steps:
    - id: create-pr
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
      with:
        commit-message: ${{ inputs.commit-message }}
        title: ${{ inputs.commit-message }}
        labels: ${{ inputs.labels }}
        add-paths: ${{ inputs.add-paths }}
        token: ${{ inputs.github-token }}
        branch: ${{ inputs.branch }}
        base: main
        draft: false
        delete-branch: true
        author: dealroomba-app[bot] <dealroomba-app[bot]@users.noreply.github.com>
        body: |
          :robot: This is an auto-generated PR
