name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read # To checkout the repository
      id-token: write # To retrieve the OIDC token
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
      - name: Get Application Token
        id: app-token
        uses: ./.github/actions/github-app-token
        with:
          application-id: ${{ secrets.DEALROOMBA_APP_ID }}
          application-private-key: ${{ secrets.DEALROOMBA_APP_PRIVATE_KEY }}
          permissions: metadata:read,contents:write,pull_requests:write,issues:write
      - name: Run Claude Code
        uses: anthropics/claude-code-action@ebbd9e9be4686249a2952e1a558bbaba07524380 # v0.0.24
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ steps.app-token.outputs.token }}
          max_turns: 200
          timeout_minutes: 30
          allowed_tools: "read_file,edit_file,list_dir,grep_search,codebase_search,run_terminal_cmd,file_search,search_replace,delete_file"
          custom_instructions: |
            - Be concise, direct to the point and actionable in responses
            - Always provide specific code solutions when requested
            - Run 'room lint --fix' after making changes if it is still failing than use 'room lint' to see and fix the errors
            - Always follow repository conventions from CLAUDE.md and .github/CLAUDE.md
