name: Test & Release

on: [push, pull_request]

permissions:
  pull-requests: write
  contents: write
  statuses: write

jobs:
  tests:
    name: Run Tests (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2", "8.3"]
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ matrix.php-version }}
      cancel-in-progress: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Get App Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@8e4e6fbf6fcc8a272781d97597969d21b3812974 # v4.0.0
        with:
          organization: dealroom
          application_id: ${{ secrets.DEALROOMBA_APP_ID }}
          application_private_key: ${{ secrets.DEALROOMBA_APP_PRIVATE_KEY }}
          permissions: "metadata:read,contents:read,packages:read"
          revoke_token: true
      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ vars.EXTENSIONS }}
          github-token: ${{ steps.get_workflow_token.outputs.token }}
      - name: Test
        uses: ./.github/actions/test
        with:
          cc-reporter-id: ${{ secrets.CC_REPORTER_ID }}
          cc-coverage-location: ${{ github.workspace }}

  test-results:
    if: ${{ always() }}
    runs-on: ubuntu-24.04
    name: Test Final Results
    needs: tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Aggregate Test Results
        uses: ./.github/actions/test-results
        with:
          needs: ${{ toJson(needs) }}

  release:
    runs-on: ubuntu-24.04
    needs: test-results
    name: Release
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: "0"
      - name: Get App Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@8e4e6fbf6fcc8a272781d97597969d21b3812974 # v4.0.0
        with:
          organization: dealroom
          application_id: ${{ secrets.DEALROOMBA_APP_ID }}
          application_private_key: ${{ secrets.DEALROOMBA_APP_PRIVATE_KEY }}
          permissions: "metadata:read,contents:write"
          revoke_token: true
      - name: Release
        uses: ./.github/actions/github-release
        with:
          github-token: ${{ steps.get_workflow_token.outputs.token }}
