name: Test & Release

on: [push, pull_request]

permissions:
  pull-requests: write
  contents: write
  statuses: write

jobs:
  tests:
    name: Run Tests (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.2']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.0
      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ vars.EXTENSIONS }}
          github-token: ${{ secrets.GH_TOKEN_DEALROOMBA }}
      - name: Test
        uses: ./.github/actions/test
        with:
          cc-reporter-id: ${{ secrets.CC_REPORTER_ID }}
          cc-coverage-location: ${{ github.workspace }}

  test-results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Test Final Results
    needs: [tests]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.0
      - name: Aggregate Test Results
        uses: ./.github/actions/test-results
        with:
          needs: ${{ toJson(needs) }}

  release:
    runs-on: ubuntu-latest
    needs: test-results
    name: Release
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: '0'
      - name: Release
        uses: ./.github/actions/release
        with:
          github-token: ${{ secrets.GH_TOKEN_DEALROOMBA }}
